## Section 1

```
1.	Write a Python program to print "Hello Python"?
2.	Write a Python program to do arithmetical operations addition and division.?
3.	Write a Python program to find the area of a triangle?
4.	Write a Python program to swap two variables?
5.	Write a Python program to generate a random number?
6.	Write a Python program to convert kilometres to miles?
7.	Write a Python program to convert Celsius to Fahrenheit?
8.	Write a Python program to display calendar?
9.	Write a Python program to solve quadratic equation?
10.	Write a Python program to swap two variables without temp variable?

```

In [1]:
## 1: Hello python 
print("Hello Python")

Hello Python


In [6]:
import random

In [11]:
random.random()


0.8066046831089839

In [32]:
## 2: Addition & division ops

class math_ops:
    def sum_ (self, a,b):
        try:
            print(a + b)
            return a + b
        except Exception as ValueError:
            print("Give Intergers / floats only....")
    def devision(self, a,b):
        try: 
            print(a/b)
            return a / b
        except Exception as ZeroDivisionError:
            print("you can't devide by Zero....")
        except Exception as ValueError:
            print(f"Give Numbers only....{ValueError}")
    def get_Area_of_triangle(self, base, hight):
        try:
            print("Triangle area=> ", (0.5 * base * hight))
        except Exception as ValueError:
            print("pass Numbers only bhai..")
    def swap_variables(self, a, b):
        print(f"Before swap a = {a}, b = {b}")
        b,a = a , b
        print(f"After swap a = {a}, b = {b}")

    def generate_random_numbers(self):
        import random
        print(random.random())

    def kmTOmiles(self,distance):
        try:
            miles =  0.621371 * distance
            print(f"{distance} Km = {miles} miles")
        except Exception as ValueError:
            print("Give numbers")
    def celc_faran(self, tempInCelcious):
        try:
           print( "celcious to faran " , (tempInCelcious * 9/5) + 32, "Faran")

        except Exception as ValueError:
            print("Give numbers only..")

    def displayCalender(self, month, year):
        print("\n"*2)
        import calendar
        cal = calendar.monthcalendar(year, month)
        print(calendar.month_name[month], year)
     
        print("Mo Tu We Th Fr Sa Su")
    
    
        for week in cal:
            # Formatting each day in the week. Days that are not part of the current month will be displayed as blanks.
            week_str = ' '.join(str(day) if day != 0 else '  ' for day in week)
            
            print(week_str)

    def solveQuadraticEq(self, a ,b ):
        print("\n"* 2 )
        try:
            print(0.2 *a + 0.4*b)
        except Exception as e:
            print(e) 
    

## 
a = math_ops()
a.sum_(2,8)
a.sum_("hey", 8 )    

a.devision(2,8)
a.devision(2,0)
a.devision(2,"hey..")

10
Give Intergers / floats only....
0.25
you can't devide by Zero....
you can't devide by Zero....


In [33]:
## Python program to find area of triangle
a.get_Area_of_triangle(base=5 , hight=5)
a.swap_variables(a=5,b=1)
a.generate_random_numbers()
a.kmTOmiles(distance=20)
a.celc_faran(tempInCelcious= 20)
a.displayCalender(month=5 , year=2021)
a.solveQuadraticEq(a= 8 , b=8 )

Triangle area=>  12.5
Before swap a = 5, b = 1
After swap a = 1, b = 5
0.5426249966044375
20 Km = 12.42742 miles
celcious to faran  68.0 Faran



May 2021
Mo Tu We Th Fr Sa Su
               1 2
3 4 5 6 7 8 9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31                  



4.800000000000001


## Section 2 

```
11.	Write a Python Program to Check if a Number is Positive, Negative or Zero?
12.	Write a Python Program to Check if a Number is Odd or Even?
13.	Write a Python Program to Check Leap Year?
14.	Write a Python Program to Check Prime Number?
15.	Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?
16.	Write a Python Program to Find the Factorial of a Number?
17.	Write a Python Program to Display the multiplication Table?
18.	Write a Python Program to Print the Fibonacci sequence?
19.	Write a Python Program to Check Armstrong Number?
20.	Write a Python Program to Find Armstrong Number in an Interval?



```

In [47]:
class section2:
    def checkpositiviy(self, num):
        try:
            print(f" Given number {num} is {'positive' if num > 0 else 'Negative'}")
        except Exception as ValueError:
            print("bro Enter intergers only...")

    def oddEven(self, num):
        try:
            print(f" Given number {num} is {'Even' if num%2 ==0 else 'odd'}")
        except Exception as ValueError:
            print("bro Enter intergers only...")
    
    
    def leapYear(self, year):
        try:
            if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
                print(f" Given Year {year} Leap")
            else:
                print(f" Given Year {year} Not Leap")
                # print()
        except Exception as ValueError:
            print("bro Enter intergers only...")

    def factorial(self, num):
        if num == 1 :
            return 1 
        else:
            return num * self.factorial(num-1)
        
    def displayMultiplicationTable(self, num):
        try:
            print(f"table of {num}")
            if type(num) == int:
                for i in range(1,11):
                    print(f"{num} * {i} = {num* i}")
            else:
                print("Pass integer..")
        except Exception as e:
            print(e)
        
    def febbonaciSeq(self, num):
        try:
            if num <= 1:
                return num
            else:
                return self.febbonaciSeq(num-1) + self.febbonaciSeq(num-2)
            
        except Exception as e:
            print(e)

    # def isArmstrongnum(self, number):
    #     ## count the number of digits
    #     num_count = 0 
    #     temp = number
    #     while temp > 0 : 
    #         temp //=10
    #         num_count += 1
        
    #     # calulate the sum digit with n power
    #     armStrongsum = 0 
    #     temp = number
    #     while temp > 0 :
    #         digit = temp % 10 
    #         armStrongsum = digit ** num_count
    #         temp //= 10 

    #     if number == armStrongsum : 
    #         print("given number is Armstrong")
    #     else:
    #         print("Given number isnot Armstrong..")

    #     return number == armStrongsum
    
    # def arMstrongIninterval(self, start, end):
    #     try:
    #         armstrongNums = []
    #         for num in range(start, end):
    #             if self.isArmstrongnum(num):
    #                 armstrongNums.append(num)
    #             else:
    #                 pass
    #         print(f"List of Armstrong nums in given range{start, end} are ==> {armstrongNums}")
    #         return armstrongNums
    #     except Exception as e:
    #         print(e)


In [44]:
a = section2()
print(a.factorial(5))
a.checkpositiviy(8)
print("\n")
a.displayMultiplicationTable(5)
print("\n")
a.febbonaciSeq(5)
print("\n")


120
 Given number 8 is positive


table of 5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50






In [50]:
def fibonacci_sequence(n):
    # Initialize the first two terms of the sequence
    fib_sequence = [0, 1]
    
    for i in range(2, n):
        next_term = fib_sequence[i-1] + fib_sequence[i-2]
        fib_sequence.append(next_term)
    
    return fib_sequence

# Example usage
num_terms = 10
fib_sequence = fibonacci_sequence(num_terms)
print("Fibonacci sequence:")
print(fib_sequence)


Fibonacci sequence:
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [48]:
def is_armstrong(number):
    num_digits = len(str(number))
    armstrong_sum = sum(int(digit) ** num_digits for digit in str(number))
    return armstrong_sum == number

def armstrong_in_interval(start, end):
    armstrong_numbers = []
    for num in range(start, end + 1):
        if is_armstrong(num):
            armstrong_numbers.append(num)
    return armstrong_numbers

# Example usage
start = 100
end = 1000
armstrong_nums = armstrong_in_interval(start, end)
print(f"Armstrong numbers between {start} and {end}:")
print(armstrong_nums)


Armstrong numbers between 100 and 1000:
[153, 370, 371, 407]


## Section 3

```
21.	Write a Python Program to Find the Sum of Natural Numbers?
22.	Write a Python Program to Find LCM?
23.	Write a Python Program to Find HCF?
24.	Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal?
25.	Write a Python Program To Find ASCII value of a character?
26.	Write a Python Program to Make a Simple Calculator with 4 basic mathematical operations?
27.	Write a Python Program to Display Fibonacci Sequence Using Recursion?
28.	Write a Python Program to Find Factorial of Number Using Recursion?
29.	Write a Python Program to calculate your Body Mass Index?
30.	Write a Python Program to calculate the natural logarithm of any number?

```

In [52]:
def get_sumNaturalNums(self, nums):
    print(sum(nums))

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def lcm(a, b):
    return (a * b) // gcd(a, b)

num1 = 12
num2 = 18
result = lcm(num1, num2)
print(f"The LCM of {num1} and {num2} is: {result}")

The LCM of 12 and 18 is: 36


In [53]:
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

# Example usage
num1 = 24
num2 = 36
result = gcd(num1, num2)
print(f"The HCF/GCD of {num1} and {num2} is: {result}")


The HCF/GCD of 24 and 36 is: 12


In [56]:
## porgram to convert decimal to binary 
# Example usage
decimal_num = 10
binary_num = bin(decimal_num)
print(binary_num)

0b1010


In [58]:
oct(decimal_num),hex(decimal_num)

('0o12', '0xa')

In [62]:
## Asci valu eof char

ord("a")

97

In [68]:
## Febbonnaci using recurrsion 

def facto(n):
    # print(n)
    if n == 1 :
        return n
    else:
        # print(n)
        return n * facto(n - 1)
    
facto(5)

120

In [69]:
def fibonacci_(n):
    if n <= 1:
        return n
    else:
        return fibonacci_(n-1) + fibonacci_(n-2)

#Runner code 
num_terms = 10
fib_sequence = [fibonacci_(i) for i in range(num_terms)]
print("Fibonacci sequence:")
print(fib_sequence)


Fibonacci sequence:
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [72]:
def bodyMassIndex(w,h):
    return w / (h**2)

bodyMassIndex(80,2)

20.0

In [73]:
import numpy as np 
np.log2(10)

3.321928094887362

In [75]:

def displayCalender( month, year):
    print("\n"*2)
    import calendar
    cal = calendar.monthcalendar(year, month)
    print("cal ", cal)
    print(calendar.month_name[month], year)
    
    print("Mo Tu We Th Fr Sa Su")


    for week in cal:
        # Formatting each day in the week. Days that are not part of the current month will be displayed as blanks.
        week_str = ' '.join(str(day) if day != 0 else '  ' for day in week)
        
        print(week_str)

displayCalender(5,2001)




cal  [[0, 1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27], [28, 29, 30, 31, 0, 0, 0]]
May 2001
Mo Tu We Th Fr Sa Su
   1 2 3 4 5 6
7 8 9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31         


## Section 4

```
31.	Write a Python Program for cube sum of first n natural numbers?
32.	Write a Python Program to find sum of array?
33.	Write a Python Program to find largest element in an array?
34.	Write a Python Program for array rotation?
35.	Write a Python Program to Split the array and add the first part to the end?
36.	Write a Python Program to check if given array is Monotonic?
37.	Write a Python Program to Add Two Matrices?
38.	Write a Python Program to Multiply Two Matrices?
39.	Write a Python Program to Transpose a Matrix?
40.	Write a Python Program to Sort Words in Alphabetic Order?
41.	Write a Python Program to Remove Punctuation From a String?
42.	Write a Python program to check if the given number is a Disarium Number?
43.	Write a Python program to print all disarium numbers between 1 to 100?
44.	Write a Python program to check if the given number is Happy Number?
45.	Write a Python program to print all happy numbers between 1 and 100?
46.	Write a Python program to determine whether the given number is a Harshad Number?
47.	Write a Python program to print all pronic numbers between 1 and 100?
48.	Write a Python program to find sum of elements in list?




```

In [78]:
def cubsum(n):
    cubsum = 0 
    for i in range(1,n):
        cubsum = cubsum + i**3
    return cubsum

cubsum(4)

36

In [83]:
## program to get sum of array
l = [1,2,3,4]
print(np.sum(np.array([1,2,3,4])))

print(sum(l))
sum_ = lambda x , y : x + y 
from functools import reduce
print(reduce(sum_ , l ))

temp = 0 
for i in l:
    temp += i 
print(temp)



10
10
10
10


In [98]:
## Python program for array rotation 
def rotate_array(arr, rotateby):
    rotated_array = arr[rotateby:] + arr[:rotateby]
    return rotated_array


l = [1,2,3,4]
rotate_array(l,3)


[4, 1, 2, 3]

In [94]:
## largest element in array
max(l)

4

In [97]:
def is_monotonic(arr):
    increasing = decreasing = True
    
    # Check if the array is monotonic increasing
    for i in range(1, len(arr)):
        if arr[i] < arr[i-1]:
            increasing = False
            break
    
    # Check if the array is monotonic decreasing
    for i in range(1, len(arr)):
        if arr[i] > arr[i-1]:
            decreasing = False
            break
    print(increasing, decreasing)
    return increasing or decreasing

# Example usage
arr1 = [1, 2, 3, 3, 4, 5]
arr2 = [7, 6, 5, 4, 3, 3, 1]
arr3 = [1, 3, 2, 5, 4]
arr4 = [4, 4, 6, 5, 3, 3, 1]

print("Is arr1 monotonic?", is_monotonic(arr1))
print("Is arr2 monotonic?", is_monotonic(arr2))
print("Is arr3 monotonic?", is_monotonic(arr3))
print("Is arr4 monotonic?", is_monotonic(arr4))


True False
Is arr1 monotonic? True
False True
Is arr2 monotonic? True
False False
Is arr3 monotonic? False
False False
Is arr4 monotonic? False


In [101]:
## python program to add two matrices

mat1 = np.array([[1,2,3,4], [5,6,7,8]])
mat2 = np.array([[1,2,3,4], [5,6,7,8]])

In [102]:
mat1 + mat2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [103]:
np.add(mat1, mat2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [104]:
mat1 * mat2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [110]:
mat4 = np.array([1,2,3,4])

In [111]:
mat1 * mat4

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [112]:
mat4 = np.array([1,2])
mat1 * mat4

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [113]:
mat1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
np.transpose(mat1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [116]:
def transpose(matx):
    transpose_mat = [] 
    for i in range(len(matx[0])) : # num of elements in one row
        transpose_row = [] 
        for j in range(len(matx)):  ## cols len 
            transpose_row.append(matx[j][i])
        transpose_mat.append(transpose_row)
    return transpose_mat

print(transpose(mat1))


[[1, 5], [2, 6], [3, 7], [4, 8]]


In [121]:
## write program to sort word in aplpha order

str_ = "hello Akash how is your python code?"
l = str_.split(" ")
l.sort()
" ".join(l)

'Akash code? hello how is python your'

In [123]:
print( list(str_) ) 

['h', 'e', 'l', 'l', 'o', ' ', 'A', 'k', 'a', 's', 'h', ' ', 'h', 'o', 'w', ' ', 'i', 's', ' ', 'y', 'o', 'u', 'r', ' ', 'p', 'y', 't', 'h', 'o', 'n', ' ', 'c', 'o', 'd', 'e', '?']


In [126]:
## program to remove punctuations
import string

def remove_punt(text):
    punct_chars = string.punctuation 
    ## list comprehension 
    text_withtout_puncts = "".join([ x for x in text if x not in punct_chars])
    print(text_withtout_puncts)

In [127]:
remove_punt("Hello! Aksah? / how asaa * lkj ads7 ")

Hello Aksah  how asaa  lkj ads7 


In [128]:
import re 

def remove_punctuation(text):
    pattern = r'[^\w\s]'
    
    # Use regex substitution to remove punctuation
    text_without_punctuation = re.sub(pattern, '', text)
    
    return text_without_punctuation

remove_punctuation("Hello! Aksah? / how asaa * lkj ads7 ")


'Hello Aksah  how asaa  lkj ads7 '

In [138]:
## disarim 89 ==> 8 ^1 + 9 ^ 2 = 8 + 81 = 89 hence it is disarium 


def isDisarium(num):
    str_n = str(num)
    dig_sum = sum(int(x)**(i + 1 ) for i , x in enumerate(str_n))
    return num == dig_sum

isDisarium(50),isDisarium(89)


(False, True)

In [151]:
## disraium betn  1 to 100 
disrList = [] 
for i in range(1,1001):
    if isDisarium(i):
        disrList.append(i)

print(disrList)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 89, 135, 175, 518, 598]


In [152]:
def happy_number(n):
    seen = set()
    while n != 1 and n not in seen:
        seen.add(n)
        n = sum(int(digit) ** 2 for digit in str(n))
    return n == 1

# Example usage
number = 19
if happy_number(number):
    print(f"{number} is a happy number.")
else:
    print(f"{number} is not a happy number.")


19 is a happy number.


In [153]:
## program to print all phonic numbers
def generate_phonic_numbers(nubmer):
    phonic_numbers = []
    for a in range(nubmer + 1):
        for b in range(nubmer + 1):
            for c in range(nubmer + 1):
                number = 2 ** a * 3 ** b * 5 ** c
                if number <= nubmer:
                    phonic_numbers.append(number)
    return sorted(phonic_numbers)


nubmer = 100
phonic_numbers = generate_phonic_numbers(nubmer)
print("Phonic numbers up to", nubmer, ":")
print(phonic_numbers)


Phonic numbers up to 100 :
[1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, 16, 18, 20, 24, 25, 27, 30, 32, 36, 40, 45, 48, 50, 54, 60, 64, 72, 75, 80, 81, 90, 96, 100]


In [154]:
## get the sum of all list elemtns


l = [1,2,3,4]
a= 0 
for  i in l :
    a += i 


In [155]:
print(a)

10


```
49.	Write a Python program to  Multiply all numbers in the list?
50.	Write a Python program to find smallest number in a list?
51.	Write a Python program to find largest number in a list?
52.	Write a Python program to find second largest number in a list?
53.	Write a Python program to find N largest elements from a list?
54.	Write a Python program to print even numbers in a list?
55.	Write a Python program to print odd numbers in a List?
56.	Write a Python program to Remove empty List from List?
57.	Write a Python program to Cloning or Copying a list?
58.	Write a Python program to Count occurrences of an element in a list?
59.	Write a Python program to find words which are greater than given length k?
60.	Write a Python program for removing i-th character from a string?
61.	Write a Python program to split and join a string?
62.	Write a Python to check if a given string is binary string or not?
63.	Write a Python program to find uncommon words from two Strings?
64.	Write a Python to find all duplicate characters in string?
65.	Write a Python Program to check if a string contains any special character?
66.	Write a Python program to Extract Unique values dictionary values?
67.	Write a Python program to find the sum of all items in a dictionary?
68.	Write a Python program to Merging two Dictionaries?
69.	Write a Python program to convert key-values list to flat dictionary?
70.	Write a Python program to insertion at the beginning in OrderedDict?
```

In [206]:
my_dict = {'a': 10,  'c': 30,'b': 20, 'cython': 2, 'Java': 2}

sorted(my_dict.items(), key = lambda x : x[1], reverse=True)

[('c', 30), ('b', 20), ('a', 10), ('cython', 2), ('Java', 2)]

In [199]:
## sotrt dict by key values
my_dict = {'a': 10,  'c': 30,'b': 20, 'cython': 2, 'Java': 2}

sorted_dict = dict(sorted(my_dict.items()))

print(sorted_dict)


{'Java': 2, 'a': 10, 'b': 20, 'c': 30, 'cython': 2}


In [196]:
from collections import OrderedDict

ordered_dict = OrderedDict()

ordered_dict['first'] = 1
ordered_dict['second'] = 2
ordered_dict['third'] = 3


print("OrderedDict after initial insertions:", ordered_dict)

ordered_dict.move_to_end('third', last=False)
ordered_dict['new_first'] = 0

print( ordered_dict)


OrderedDict after initial insertions: OrderedDict([('first', 1), ('second', 2), ('third', 3)])
OrderedDict([('third', 3), ('first', 1), ('second', 2), ('new_first', 0)])


In [ ]:
## instert at the beginning of dict
my_dict = {'a': 10, 'b': 20, 'c': 30, 'python': 2, 'Java': 2}
my_dict.update()

In [193]:
## key value to flat list to flat dict
my_dict = {'a': 10, 'b': 20, 'c': 30, 'python': 2, 'Java': 2}

list(my_dict.items())


[('a', 10), ('b', 20), ('c', 30), ('python', 2), ('Java', 2)]

In [191]:
## merge two dict 
my_dict = {'a': 10, 'b': 20, 'c': 30}
dict2 = {"python": 2 , "Java" :2 }

my_dict.update(dict2)
my_dict

{'a': 10, 'b': 20, 'c': 30, 'python': 2, 'Java': 2}

In [188]:
## Extract sum of all dict items
my_dict = {'a': 10, 'b': 20, 'c': 30}

total_sum = sum(value for value in my_dict.values())

print("Sum of all values in the dictionary:", total_sum)

Sum of all values in the dictionary: 60


In [186]:
## check if binary string or not 

text = "1001"
flag = ""

for x in text:
    if ( x!= "0" ) or (x!= "1"):
        flag = False
   
    flag = True

flag

True

In [179]:
## find all duplicate chars in str 
text = "given sentence is find the word is are greater than given len k "
dup_char = dict()
for i in text:
    if i in dup_char.keys():
        dup_char[i] += 1 
    else:
        dup_char[i] = 1 


for key, val in dup_char.items():
    if val > 1 :
        print( f"key {key} ==> Value {val}")



key g ==> Value 3
key i ==> Value 5
key v ==> Value 2
key e ==> Value 10
key n ==> Value 7
key   ==> Value 13
key s ==> Value 3
key t ==> Value 4
key d ==> Value 2
key h ==> Value 2
key r ==> Value 4
key a ==> Value 3


In [177]:
## remove k'th char from string
k = 1
text = "given sentence is find the word is are greater than given len k "
l = text.split( " ")
" + ".join(l[ : k] + l [k+1 : ])


'given + is + find + the + word + is + are + greater + than + given + len + k + '

In [174]:
## finc word split and join string
k = 4
text = "given sentence is find the word is are greater than given len k "
" + ".join(text.split( " "))

'given + sentence + is + find + the + word + is + are + greater + than + given + len + k + '

In [173]:
## finc word which are greater than given len k 
k = 4
text = "given sentence is find the word is are greater than given len k "
l= text.split(" ")
list(filter(lambda x : True if len(x) < k else  False, l ))

['is', 'the', 'is', 'are', 'len', 'k', '']

In [170]:
## count occurence of element in list
l = [1,1,1,1,5,5,5,5,2,4]
occ_ = dict()

for i in range(0 , len(l)): 
    if l[i] not in occ_.keys():
        occ_[l[i]] = 1 
    else:
        occ_[l[i]] += 1 

occ_


{1: 4, 5: 4, 2: 1, 4: 1}

In [166]:
## copy the list 
a = [1,2,32,5]
b = a.copy()
b

[1, 2, 32, 5]

In [164]:
## remove empty lisr from list
l = [1,2,3,4,[1,4], []]
l.remove([])
print(l)

[1, 2, 3, 4, [1, 4]]


In [163]:
# print odd numbers in list
l = [4,89,21,7,6,7,46,88]
list(filter(lambda x : True if x%2 != 0 else False , l  ))

[89, 21, 7, 7]

In [162]:
# print Even numbers in list
l = [4,89,21,7,6,7,46,88]
list(filter(lambda x : True if x%2 == 0 else False , l  ))

[4, 6, 46, 88]

In [156]:
## multiply all nums in list

## get the sum of all list elemtns


l = [1,2,3,4]
a= 1 
for  i in l :
    a *= i 
a

24

In [157]:
## smallest number in list

l = [1,2,3,4 , 0.2]

temp = 88991519919545 
for i in l :
    if i < temp:
        temp = i 
temp

0.2

In [158]:
## largest number in list

l = [1,2,3,4 , 0.2]

temp = - 88991519919545 
for i in l :
    if i > temp:
        temp = i 
temp

4

In [160]:
## N Largest from list
l.sort(reverse=True)
n = 2 
l[n-1]

3